AppBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        createdAt:
            type: datetime
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: categories
            joinColumn:
               name: user_id
               referencedColumnName: id
    oneToMany:
        transactions:
            targetEntity: AppBundle\Entity\Transaction
            mappedBy: category
    lifecycleCallbacks: {  }
