AppBundle\Entity\Payment:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PaymentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        logo:
            type: string
            length: 255
            nullable: true
        isDefault:
            type: boolean
        createdAt:
            type: datetime
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: payments
            joinColumn:
                name: user_id
                referencedColumnName: id
    oneToMany:
        transactions:
            targetEntity: AppBundle\Entity\Transaction
            mappedBy: payment
    lifecycleCallbacks: {  }
