AppBundle\Entity\Payment:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PaymentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: payments
            joinColumn:
                name: user_id
                referencedColumnName: id
    oneToOne:
        transaction:
            targetEntity: AppBundle\Entity\Transaction
            inversedBy: payment
            joinColumn:
                name: transaction_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
