AppBundle\Entity\Transactions:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TransactionsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: integer
    manyToOne:
        payment:
            targetEntity: AppBundle\Entity\Payment
            inversedBy: transactions
            joinColumn:
                name: payment_id
                referencedColumnName: id
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: transactions
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
