AppBundle\Entity\Transaction:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TransactionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        amount:
            type: float
        comment:
            type: text
        createdAt:
            type: datetime
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: transactions
            joinColumn:
                name: user_id
                referencedColumnName: id
        category:
            targetEntity: AppBundle\Entity\Category
            inversedBy: transactions
            joinColumn:
                name: category_id
                referencedColumnName: id
        payment:
            targetEntity: AppBundle\Entity\Payment
            inversedBy: transactions
            joinColun:
                name: payment_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
