AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        country:
            type: string
            length: 100
        currency:
            type: string
            length: 50;
    oneToMany:
        categories:
            targetEntity: AppBundle\Entity\Category
            mappedBy: user