category_new:
    path: /category/
    defaults: { _controller: AppBundle:Category:new }

category_edit:
    path: /category/{id}/edit
    defaults: { _controller: AppBundle:Category:edit }

category_delete:
    path: /category/{id}/delete
    defaults: { _controller: AppBundle:Category:delete }